site_name: Carnival System Manual
plugins:
  - search
nav:
    - Home: index.md
    - Staff User: user.md
    - Contract: contract.md
    - Client: client.md
    - Config: config.md
  
theme: readthedocs